laravel/app/routes.php
<?php

// Front

Route::get('/', array(
    'as'   => 'home',
    'uses' => 'HomeController@index'
));

Route::get('home', array(
    'as'   => 'home',
    'uses' => 'HomeController@index'
));

Route::get('fetchInstagram', function(){
    if (!Request::ajax()) return;

    $instagram_imagens = Instagram::get_images();
    return View::make('frontend.home.instagram', compact('instagram_imagens'));
});

Route::get('perfil', array(
    'as'   => 'perfil',
    'uses' => 'PerfilController@index'
));

Route::get('nossos-servicos', array(
    'as'   => 'nossos-servicos',
    'uses' => 'ServicosController@index'
));

Route::get('como-funciona', array(
    'as'   => 'como-funciona',
    'uses' => 'ComoFuncionaController@index'
));

Route::post('envioOrcamento', array(
    'as'   => 'como-funciona.envio',
    'uses' => 'ComoFuncionaController@envio'
));

Route::get('trabalhe-conosco', array(
    'as'   => 'trabalhe-conosco',
    'uses' => 'TrabalheConoscoController@index'
));

Route::post('envioTrabalhe', array(
    'as'   => 'trabalhe-conosco.envio',
    'uses' => 'TrabalheConoscoController@envio'
));

Route::get('contato', array(
    'as'   => 'contato',
    'uses' => 'ContatoController@index'
));

Route::post('envioContato', array(
    'as'   => 'contato.envio',
    'uses' => 'ContatoController@envio'
));


// Painel

Route::get('painel', array(
    'before' => 'auth',
    'as'     => 'painel.home',
    'uses'   => 'Painel\HomeController@index'
));

Route::get('painel/login', array(
    'as'   => 'painel.login',
    'uses' => 'Painel\HomeController@login'
));

Route::post('painel/login',  array('as' => 'painel.auth', function() {
    $authvars = array(
        'username' => Input::get('username'),
        'password' => Input::get('password')
    );

    if (Auth::attempt($authvars)) return Redirect::to('painel');

    Session::flash('login_errors', true);
    return Redirect::to('painel/login');
}));

Route::get('painel/logout', array('as' => 'painel.off', function() {
    Auth::logout();
    return Redirect::to('painel');
}));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function() {
    Route::resource('imagens', 'Painel\ImagensController');
    Route::resource('perfil', 'Painel\PerfilController');
    Route::resource('comoFunciona', 'Painel\ComoFuncionaController');
    Route::resource('comoFuncionaRecebidos', 'Painel\ComoFuncionaRecebidosController');
    Route::resource('trabalheConosco', 'Painel\TrabalheConoscoController');
    Route::resource('trabalheConoscoRecebidos', 'Painel\TrabalheConoscoRecebidosController');
    Route::resource('contato', 'Painel\ContatoController');
    Route::resource('contatosRecebidos', 'Painel\ContatosRecebidosController');
    Route::resource('usuarios', 'Painel\UsuariosController');
});

laravel/app/controllers/painel/UsuariosController.php
<?php

namespace Painel;

use \User, \View, \Input, \Session, \Redirect, \Hash;

class UsuariosController extends BaseAdminController {

    protected $layout = 'backend.template.index';

    public function index()
    {
        $this->layout->content = View::make('backend.usuarios.index')
            ->with('usuarios', User::all());
    }

    public function create()
    {
        $this->layout->content = View::make('backend.usuarios.form');
    }

    public function store()
    {
        $object = new User;

        $object->email = Input::get('email');
        $object->username = Input::get('username');
        $object->password = Hash::make(Input::get('password'));

        if (!Input::get('username') || !Input::get('password') || (Input::get('password') != Input::get('password_confirm'))){
            Session::flash('formulario', Input::all());
            return Redirect::back()->withErrors(array('Erro ao criar usuário! Verifique se os campos estão devidamente preenchidos e que a confirmação de senha é igual à senha informada'));
        } else {
            try {

                $object->save();
                Session::flash('sucesso', true);
                Session::flash('mensagem', 'Usuário criado com sucesso.');
                return Redirect::route('painel.usuarios.index');

            } catch (\Exception $e) {

                Session::flash('formulario', Input::all());
                return Redirect::back()->withErrors(array('Erro ao criar usuário! Verifique se o nome de usuário ou o email não estão sendo utilizados.'));

            }
        }
    }

    public function show($id) {}

    public function edit($id)
    {
        $this->layout->content = View::make('backend.usuarios.edit')
            ->with('usuario', User::find($id));
    }

    public function update($id)
    {
        $object = User::find($id);

        $object->email = Input::get('email');
        $object->username = Input::get('username');

        if (Input::has('password')) {
            if (Input::get('password') == Input::get('password_confirm')) {
                $object->password = Hash::make(Input::get('password'));
            } else {
                Session::flash('formulario', Input::all());
                return Redirect::back()->withErrors(array('Erro ao criar usuário! Verifique se os campos estão devidamente preenchidos e que a confirmação de senha é igual à senha informada'));
            }
        }

        if (!Input::get('username')) {
            Session::flash('formulario', Input::all());
            return Redirect::back()->withErrors(array('Erro ao criar usuário! Verifique se os campos estão devidamente preenchidos e que a confirmação de senha é igual à senha informada'));
        } else {
            try {

                $object->save();
                Session::flash('sucesso', true);
                Session::flash('mensagem', 'Usuário alterado com sucesso.');
                return Redirect::route('painel.usuarios.index');

            } catch (\Exception $e) {

                Session::flash('formulario', Input::all());
                return Redirect::back()->withErrors(array('Erro ao criar usuário! Verifique se o nome de usuário ou o email não estão sendo utilizados.'));

            }
        }
    }

    public function destroy($id) {
        $object = User::find($id);
        $object->delete();

        Session::flash('sucesso', true);
        Session::flash('mensagem', 'Usuário removido com sucesso.');

        return Redirect::route('painel.usuarios.index');
    }

}

laravel/app/views/backend/usuarios/edit.blade.php
@section('content')

    <legend>
        <h2>Editar Usuário</h2>
    </legend>

    {{ Form::open( array('route' => array('painel.usuarios.update', $usuario->id), 'files' => false, 'method' => 'put') ) }}
        <div class="pad">

            @if(Session::has('sucesso'))
               <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
            @endif

            @if($errors->any())
                <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
            @endif

            <div class="form-group">
                <label for="inputUsuario">Usuário</label>
                <input type="text" class="form-control" id="inputUsuario" name="username" value="{{$usuario->username}}" required>
            </div>

            <div class="form-group">
                <label for="inputEmail">E-mail</label>
                <input type="email" class="form-control" id="inputEmail" name="email" value="{{$usuario->email}}">
            </div>

            <div class="form-group">
                <label for="inputSenha">Senha</label>
                <input type="password" class="form-control" id="inputSenha" name="password" required>
            </div>

            <div class="form-group">
                <label for="inputConfSenha">Digite novamente a Senha</label>
                <input type="password" class="form-control" id="inputConfSenha" name="password_confirm" required>
            </div>

            <button type="submit" title="Inserir" class="btn btn-success">Alterar</button>

            <a href="{{URL::route('painel.usuarios.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

        </div>
    </form>

@stop

laravel/app/views/backend/usuarios/form.blade.php
@section('content')

    <legend>
        <h2>Adicionar Usuário</h2>
    </legend>

    <form action="{{URL::route('painel.usuarios.store')}}" method="post">
        <div class="pad">

            @if(Session::has('sucesso'))
               <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
            @endif

            @if($errors->any())
                <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
            @endif

            <div class="form-group">
                <label for="inputUsuario">Usuário</label>
                <input type="text" class="form-control" id="inputUsuario" name="username"  @if(Session::has('formulario')) value="{{ Session::get('formulario.username') }}" @endif required>
            </div>

            <div class="form-group">
                <label for="inputEmail">E-mail</label>
                <input type="email" class="form-control" id="inputEmail" name="email" @if(Session::has('formulario')) value="{{ Session::get('formulario.email') }}" @endif>
            </div>

            <div class="form-group">
                <label for="inputSenha">Senha</label>
                <input type="password" class="form-control" id="inputSenha" name="password" required>
            </div>

            <div class="form-group">
                <label for="inputConfSenha">Digite novamente a Senha</label>
                <input type="password" class="form-control" id="inputConfSenha" name="password_confirm" required>
            </div>

            <button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

            <a href="{{URL::route('painel.usuarios.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

        </div>
    </form>

@stop

laravel/app/views/backend/usuarios/index.blade.php
@section('content')

    @if(Session::has('sucesso'))
       <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <legend>
    <h2>
        Usuários <a href="{{ URL::route('painel.usuarios.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus-sign"></span> Adicionar Usuário</a>
    </h2>
    </legend>

    <table class="table table-striped table-bordered table-hover ">
        <thead>
            <tr>
                <th>Usuário</th>
                <th>E-mail</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($usuarios as $usuario)

            <tr class="tr-row">
                <td>
                    {{ $usuario->username }}
                </td>
                <td>
                    {{ $usuario->email }}
                </td>
                <td class="crud-actions">
                    <a href="{{ URL::route('painel.usuarios.edit', $usuario->id ) }}" class="btn btn-primary btn-sm pull-left">editar</a>
                    @if(Auth::user()->id != $usuario->id)
                       {{ Form::open(array('route' => array('painel.usuarios.destroy', $usuario->id), 'method' => 'delete')) }}
                            <button type="submit" class="btn btn-danger btn-sm btn-delete">excluir</button>
                       {{ Form::close() }}
                   @endif
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

@stop